### ISSUE TITLE
whypfs-gateway details

### ISSUE THREAD

**Issue by snissn** [Zorlin/whyweedpfs-playbook#1]
```


git clone https://github.com/application-research/whypfs-gateway.git
cd whypfs-gateway
go mod tidy
go mod download
go build -tags netgo -ldflags '-s -w' -o whypfs-gw
./whypfs-gw
```

currently whypfs uses by default a directory path in the current working direcotyr named 
`.whypfs/blocks`

i think in the short term that's fine, we can just do some relative / absolute path magic and cd into our seaweedfs directory and then use the absolute path of whypfs-gw

so something like this works great
```
SEAWEEDDIR=/tmp #TODO Change if needed
git clone https://github.com/application-research/whypfs-gateway.git
cd whypfs-gateway
go mod tidy
go mod download
go build -tags netgo -ldflags '-s -w' -o whypfs-gw
cmd=`pwd`/whypfs-gw
cd $SEAWEEDDIR
"$cmd"
```

when the ticket to pass in path for flatfs is updated we can clean this code up  if we feel a need: https://github.com/application-research/whypfs-gateway/issues/5

also looks like we need to set up a reverse proxy because whypfs-gateway lists on port 1313 (or we can change that port, but i think a proxy is good)

**Comment by Zorlin** [comment]
At the moment we just run it where we run it (I forget exactly where that
is, but it's defined in the playbook) and symlink the blocks folder into
Seaweed. This allows us to have both node-specific files and
node-independent (ie stored on seaweed) files.

**Comment by snissn** [comment]
a sym link resolves this great!

**Comment by Zorlin** [comment]
> also looks like we need to set up a reverse proxy because whypfs-gateway lists on port 1313 (or we can change that port, but i think a proxy is good)

👍 Sounds good
